name: (master) push to external repo
on:
  push:
    branches:
      - master
jobs:
  push-to-external-repo:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: push to external repository
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.SSH_DEPLOY_KEY_WEBSITE }}
          publish_dir: .
          external_repository: Marrmee/psd_website
          publish_branch: main
          allow_empty_commit: true